"""empty message

Revision ID: 62440bbe6340
Revises: 7020a3d1be42
Create Date: 2022-09-21 14:47:12.799988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62440bbe6340'
down_revision = '7020a3d1be42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salt',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
